server:
  port: 8855

spring:
  application:
    name: cloud-turbine-server

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

config:
  info: master branch,springcloud-config/config-dev.yml version=1
